# Cloud Native Buildpacks â€” descriptor del proyecto
# Uso: pack build prodaric-framework [--builder paketobuildpacks/builder-jammy-base]

schema-version = "0.2"
id = "org.prodaric.framework"
name = "Prodaric Framework"
version = "0.1.0"

[[io.buildpacks.build.env]]
name = "NODE_ENV"
value = "production"
